### ISSUE TITLE
[Suggestion] Put an oxygen recycler in the escape pods and solitary cells of brig

### ISSUE THREAD

**Issue by AGasCanister** [DS-13-Dev-Team/DS13#488]
Body (for suggestions):
Suggestion:
An oxygen recycler that automatically turns carbon dioxide into oxygen

What do you think it'd add:
Currently if you escape via a escape pod and wait around 5-7 minutes you will start being affected by carbon dioxide, which will give you some red messages (you feel dizzy) and then it will kill you after inhaling too much carbon dioxide.

This also happens with the solitary cells of brig, they have no vents and no scrubbers so the same things happens, but it takes more time, as they have 4 tiles instead of 2 (pods).

**Comment by NanakoAC** [comment]
the brig cells seem like a mapping issue

As for the escape pods, how do other servers handle this?

**Comment by AGasCanister** [comment]
Normally you don't stay in a pod 5-7 minutes, on other servers they usually land in a station/ship after around 3 minutes, or the round simply ends before they can die.

**Comment by Snypehunter007** [comment]
We should probably cut down the time it takes till the pods auto-launch anyways.

I'll set this suggestion to accepted and fix the solitary cells. I **_think_** the only reason they aren't in there currently is because of a worry about Necros popping in and just murdering in the prisoner (before we knew how long it would take till the vent system was re-done).

**Comment by Snypehunter007** [comment]
I believe #485 was the one were I put in the brig solitary cell fix in.
